<div class="page-wrapper">

      <div class="container-fluidic container-tv-header">

          <div class="container">

              <?php $this->load->view('site/includes/menu');?>

              <div class="clearfix"></div>

              <div class="page-title">
                <h1 class="grd-txt">Privacy Policy</h1>
              </div>

              <div class="clearfix"></div>

              <div class="block row mt-md blog-content">

                  <div class="col-lg-12">
                    <p class="p0"><span class="c0">This website is operated by Herotainment, LLC (&ldquo;Herotainment&rdquo;), a U.S. company with offices in New York, NY. Herotainment is committed to providing a fun, friendly and safe game for all ages while protecting and safeguarding consumer privacy on the Internet, especially for children. This privacy policy (&ldquo;Privacy Policy&rdquo;) describes how we handle the personal information provided to us through Herotainment Games (&ldquo;Games&rdquo;) or any online or mobile product operated by Herotainment (collectively with Games, the &ldquo;Services&rdquo;).</span></p>
<p class="p1"><span class="c0">Please be sure to read this Privacy Policy before using the Services or submitting information to us. Our Privacy Policy may change from time to time and by installing, using or otherwise accessing the Services and your continued use of our Services constitutes acceptance of this Privacy Policy and consent to the use of your personal information as described herein. Please check this area periodically for updates to this Privacy Policy.</span></p>
<p class="p2"><span class="c0">Herotainment is very sensitive to privacy issues with respect to children, especially those under the age of 13. Please see below for more information on how Herotainment addresses children&rsquo;s privacy issues generally and under the Children&rsquo;s Online Privacy Protection Act (&ldquo;COPPA&rdquo;). We encourage parents to regularly monitor and supervise their child&rsquo;s on-line activities.</span></p>
<p class="p3"><span class="c0">In this Privacy Policy we describe what information we collect, how we collect it, and what we do with it (the Privacy Policy covers only information collected and used with our Services). Herotainment strives to comply with the Children&rsquo;s Online Privacy Protection Act, (COPPA) a U.S. law that governs the use and collection of information online from children under the age of 13.</span></p>
<h2 class="p4">THE INFORMATION WE COLLECT AND HOW WE COLLECT IT</h2>
<p class="p6">When users register for or use some of our Services, Herotainment sometimes asks them to select a username and password, birthdate and gender, and for children under the age of 13, to provide his or her parent&rsquo;s email address. Herotainment requires users under the age of 13 to provide a parent&rsquo;s valid email address so that we may send the parent an email message in connection with the creation of the account. We do not knowingly collect information from users under the age of 13. Users 13 or older will provide their own email address. In the use of the Services, no additional information is collected.</p>
<p class="p8"><span class="c0">Also, we may collect identifiable information from our users in response to poll, forums and promotional offers. We use this information to contact you about the services on the Services in which you have expressed interest. Occasionally, Herotainment sends out updates regarding new Services features, via parent announcements and a newsletter. We also may need to contact you regarding any customer service queries you submit, such as password retrieval.</span></p>
<p class="p9"><span class="c0">As part of the registration process, we may require limited demographic information (gender and birth date); we encourage you to submit this information so we can provide you a more personalized experience. We limit the information we collect, both actively (i.e., what we ask) &nbsp;and passively (what we collect through use of web tracking mechanisms like &ldquo;cookies,&rdquo;) to that which is necessary for users to take part in a particular Services activity.</span></p>
<p class="p10"><span class="c0">Herotainment is the sole owner of the information collected on the Services. Herotainment collects personally identifiable information from our users at several different points on our Services, including registration and customer service contact queries.</span></p>
<p class="p11"><span class="c0">When a user pays for certain features or purchases merchandise from some of the Services, we request certain personally identifiable information from you on your order form and if under the age of 13, from that user&rsquo;s parent. The types of personally identifiable information that may be collected at that time include the user&rsquo;s full name, email address, and credit card billing information including mailing address or other payment information. If the user is under 13, we would collect the parent&rsquo;s full name, email address, and credit card billing or payment information including mailing address.</span></p>
<p class="p12"><span class="c0">We collect financial information as set out in this section of this Privacy Policy but don&rsquo;t use this financial information for any purposes other than processing payments to the Services. The financial information that you enter to purchase certain features or merchandise is not stored by Herotainment, but, instead, is retained by our payment processing vendors for the purpose of processing credit card payments or other payment methods to the Services.</span></p>
<p class="p13"><span class="c0">Although, we do not generally give your personal information to third parties, we may disclose your information to Herotainment&rsquo;s partners and vendors who provide technical support or other services to Herotainment related to the Services. For example, we use other third parties such as a shipping company to fulfill merchandise orders, and a credit card processing company to bill you for certain features and merchandise. We may use email and the telephone to assist you if you have questions while using the Services or regarding your order. When you pay using one of our payment vendors, we will share your email address, and Account ID as necessary for the third party to provide that service.</span></p>
<p class="p14"><span class="c0">Additionally, when visitors come to our Services, we may passively collect certain non-personally identifiable computer information, such as the type of computer operating system, the user&rsquo;s IP Address, device properties such as (a) unique device identifier (&ldquo;UDID&rdquo;), Media Access Control (&ldquo;MAC&rdquo;) Address, or other device identifiers (b) device software platform, firmware and manufacturer; (c) mobile phone carrier; geographical information such as zip code, area code, internet protocol (&ldquo;IP&rdquo;) address and location; and (e) other Non-personally Identifying Information, the web browser being used, the frequency with which users visit various parts of our Services, and information regarding the Internet service provider, in order to make our Services more interesting and useful to you for various purposes related to our business. We may also collect this non-personally identifiable information through the use of software technologies such as unique identifiers or &ldquo;cookies&rdquo;. A cookie is a small text file that is stored on a user&rsquo;s computer for record-keeping purposes. We use cookies on our Services. We link the information we store in cookies to personally identifiable information you submit while on our Services. Cookies are small text files that we place in visitors&rsquo; computer browsers to store their preferences. Our cookies themselves do not contain any personally identifiable information. Our cookies reference the personally identifiable information you provided during registration. We reference the information you provided via an encrypted identifier. Where we link these unique identifiers with your personally identifiable information, we will treat the unique identifiers as personally identifiable information as long as they are linked. We use the registration information you provided to contact you if you lose your password or contact you about Services updates and changes.</span></p>
<p class="p15"><span class="c0">We use both session ID cookies and persistent cookies. We use session cookies to make it easier for you to navigate our Services. A session ID cookie expires when you close your browser. A persistent cookie remains on your hard drive for an extended period of time. You can remove persistent cookies by following directions provided in your Internet browser&rsquo;s &ldquo;help&rdquo; file.</span></p>
<p class="p16"><span class="c0">If you turn cookies off, you won&rsquo;t have access to many features that make your Services experience smoother, and some of our services may not function properly.</span></p>
<p class="p17"><span class="c0">The use of cookies by our affiliates and/or service providers is not covered by our Privacy Policy. We do not have access or control over these cookies. Our affiliates or service providers use session ID cookies to provide demographic and metrics information to Herotainment and to make it easier for you to navigate the Services, in order for you to use the subscription service.</span></p>
<p class="p18"><span class="c0">If you choose to use our referral service to tell a friend about our Services, we will ask for your friend&rsquo;s information to send a message. We will automatically send your friend a one-time message invite but we don&rsquo;t store your friend&rsquo;s information.</span></p>
<p class="p19"><span class="c0">We may also employ third-party ad serving and/or analytics technologies that use certain methods to collect information through the Services. These technologies may be imbedded with the Services and may collect demographic and location information as well as information from your device including, but not limited to IP address, UDID, software, applications, hardware, browser information, internet and on-line usage information and in-game information.</span></p>
<h2 class="p20">OTHER INFORMATION WE COLLECT WHEN YOU USE OUR PRODUCTS</h2>
<p class="p22"><span class="c0">We collect other information automatically when you use our Services, including:</span></p>
<p class="p23"><span class="c0">IP address;</span></p>
<p class="p24"><span class="c0">Mobile and other hardware or device identifiers;</span></p>
<p class="p25"><span class="c0">Browser information, including your browser type and the language you prefer;</span></p>
<p class="p26"><span class="c0">Referring and exit pages, including landing pages and pages viewed;</span></p>
<p class="p27"><span class="c0">Platform type;</span></p>
<p class="p28"><span class="c0">Information about your media, device, hardware and software, such as your hardware settings and components;</span></p>
<p class="p29"><span class="c0">Details about what Herotainment products you use and your use of them; and</span></p>
<p class="p30"><span class="c0">Device event information, including crash reports, request and referral URL's and system activity details (e.g. whether you encountered an error playing our games or lost Internet access).</span></p>
<p class="p31"><span class="c0">We also may collect and store information locally on your device, using mechanisms like cookies, browser web storage (including HTML 5) and application data caches.</span></p>
<p class="p32">Mobile Platforms. If you play or purchase our Services on your mobile device and/or tablet, we receive information about you from the app stores and other mobile platform providers. This information includes your username and/or device ID and the fact that you made a purchase, for instance, but does not include any sensitive or financial information. Some of our mobile platforms also may send information to us that you authorize them to provide. Our mobile products also may request additional personal information from you, such as push notification tokens, your precise location or contact list, and we will collect this information only if you give us your explicit consent.</p>
<h2 class="p34">OTHER PERMISSIONS</h2>
<p class="p36"><span class="c0">Our games may request permissions to your device camera, microphone, accounts and contacts or user data.</span></p>
<h2 class="p37">ANALYTICS TECHNOLOGIES</h2>
<p class="p39"><span class="c0">We may use our own game servers and internal and third party analytic technologies to collect information about how you use our products, your computer or device and the health of our products.</span></p>
<p class="p40"><span class="c0">For instance, Herotainment may collect and store data from your computer or device when you use our products. This information includes technical and related information about your computer or device and operating system (such as IP Address and device ID), information about your feature usage, gameplay and usage statistics and system interactions. If you play a game offline, this data will be stored on your device and transmitted to Herotainment when your device connects to the Internet.</span></p>
<p class="p41"><span class="c0">Third party analytics services integrated into our products may combine the information they collect in connection with Herotainment&rsquo;s services with information they have independently collected over time and across different websites.</span></p>
<h2 class="p42">AD SERVING TECHNOLOGIES</h2>
<p class="p44"><span class="c0">Some of our Services employ ad serving technologies that use cookies, clear GIFs, web beacons, tracking pixels, and other similar technologies like identifiers to deliver offers to you. Some of these technologies can sync or connect behavior across different websites, mobile apps and devices. The ads can be tailored to your interests. For instance, you may be presented with an offer for a game we think you might enjoy. Or if you express interest in a game, you might receive an advertisement later for that game or similar products. Other in-game advertising technologies enable advertising to be temporarily uploaded to your game, web browser, or mobile device and later replaced while you are online.</span></p>
<p class="p45"><span class="c0">These technologies collect and use information so we can serve appropriate advertising to you and help track results and measure effectiveness. In addition to identifiers, this information includes:</span></p>
<p class="p46"><span class="c0">Advertisements served and the location of the ad;</span></p>
<p class="p47"><span class="c0">Length of time an advertisement was visible;</span></p>
<p class="p48"><span class="c0">Domain type, IP address, size of the advertisement; and</span></p>
<p class="p49"><span class="c0">Advertisement response.</span></p>
<p class="p50"><span class="c0">Third party advertising companies may combine the information collected in the context of delivering an ad to you via our Services with other information they have independently collected over time and across different websites.</span></p>
<h2 class="p51">HOW NON-PERSONALLY IDENTIFYING INFORMATION IS USED</h2>
<p class="p53">We may collect and store your Non-Personally Identifying Information to analyze Service usage, improve and serve ads, manage and provide the Services or for any other purposes relating to improving Services and products. We may disclose Non-Personally Identifying Information to third parties and/or allow third parties to collect Non-Personally Identifying Information through embedded technology within the Services. These companies collect and use information under their own privacy policies. You acknowledge that the third parties, such as advertising and analytics specialists that receive Non-Personally Identifying Information may combine the information collected with other information they have independently collected from other services or products. If you do not want to be subject to the practices of these third parties, please do not use or access the Services.</p>
<p class="p55"><span class="c0">Whenever practicable, we will use anonymized versions of device identifiers to make it more difficult for third parties to combine the information from the Services with other information sources. Although we take commercially reasonable steps to instruct third parties to comply with the terms and conditions of this Privacy Policy, we do not have access to or control of third-party technologies.</span></p>
<h2 class="p56">SOCIAL NETWORKS</h2>
<p class="p58">Certain features of the Services may enable you to connect to social networking sites and for us to obtain additional information about you and your social network. We do not knowingly connect children under 13 with social networking sites. We may be able to collect certain Personally Identifying Information and Non-Personally Identifying Information from your social networking profile when your social networking site permits it, and when you consent to allow your social networking site to make such information available to us. This information may include, but is not limited to, your name, profile picture, gender, social network user ID, email address, your country, your language, your time zone, the organizations and links on your profile page, the names and profile pictures of your social networking site &ldquo;friends&rdquo; and other information you have included in your social networking site profile. We may associate, combine and/or use information collected through such social networking sites in accordance with this Privacy Policy.</p>
<h2 class="p60">HOW HEROTAINMENT USES THE INFORMATION IT COLLECTS</h2>
<p class="p62">If a user is under the age of 13, Herotainment uses the parent&rsquo;s email address provided at registration to notify parents that their child has created an account on our Services. In that initial notice, parents are provided a link to this Privacy Policy and the Service Terms of Use. Parent email addresses are used to communicate with parents about their child&rsquo;s activity on our Services such as a forgotten password.</p>
<p class="p64"><span class="c0">The information submitted will be used by Herotainment to create an account and will allow the registered user to participate on the Services. We also use this information to manage your use of the Services and support operation of the Services generally. We use any billing information you may provide to collect any payments due in connection with your use of the Services or for merchandise orders. We may also use your personal information to send you updates and information about the Services and Herotainment products and services.</span></p>
<p class="p65"><span class="c0">Although we do not generally give your personal information to third parties, we may disclose your information to Herotainment&rsquo;s partners and vendors who provide technical support or other services to Herotainment related to the Services. For example, we may provide your information to companies who host the Services or process credit card information. However, these vendors may not use your information for any reason other than assisting Herotainment and are required to maintain the confidentiality, security and integrity of the information.</span></p>
<p class="p66"><span class="c0">We reserve the right to disclose information if required to do so by law or by a regulatory authority. We may also disclose your information as part of an investigation or enforcement action relating to improper or illegal conduct in connection with our Services.</span></p>
<p class="p67"><span class="c0">If a third party acquires the assets of Herotainment related to the Services and its products and services (whether by sale, merger, change of control, bankruptcy or otherwise), your information may be transferred to the new owner(s). In such case, your information would remain subject to the provisions of the Privacy Policy that was applicable to your information immediately prior to the transfer.</span></p>
<p class="p68"><span class="c0">Herotainment may maintain aggregate data or other non-personally identifiable information about our users, such as usage statistics, online traffic patterns and user feedback. In addition to using this information to support operation of the Services, Herotainment may disclose this information to third parties without restriction.</span></p>
<p class="p69"><span class="c0">We may send you push notifications when you are using the Services. If you don&rsquo;t want these notifications, you can deactivate push notifications by changing your notification settings on your device. We can send you marketing communications. We may actively collect and use email addresses and usernames to track usage and to ensure users are following the Service Terms of Use. In addition, we may use an email address and username to ban a user temporarily or permanently from the Services if that user engages in inappropriate conduct on the Services.</span></p>
<p class="p70">Also, we use your personal and non-personal information, both individually and combined together, in the following ways:</p>
<p class="p72"><span class="c0">Operate, improve, and develop our games and services;</span></p>
<p class="p73"><span class="c0">Populate online leaderboards and enable online matchmaking;</span></p>
<p class="p74"><span class="c0">Help you find your friends or tell your friends about a Herotainment product or service;</span></p>
<p class="p75"><span class="c0">Facilitate sharing on social networks;</span></p>
<p class="p76"><span class="c0">Serve and measure the effectiveness of advertising;</span></p>
<p class="p77"><span class="c0">Measure the health of our services;</span></p>
<p class="p78"><span class="c0">Set up and maintain accounts you register for;</span></p>
<p class="p79"><span class="c0">Provide game experiences that you may like;</span></p>
<p class="p80"><span class="c0">Set up loyalty programs;</span></p>
<p class="p81"><span class="c0">Facilitate your gameplay on multiple devices when available;</span></p>
<p class="p82"><span class="c0">Identify, fix, and troubleshoot bugs and service errors;</span></p>
<p class="p83"><span class="c0">Provide software updates;</span></p>
<p class="p84"><span class="c0">Activate or authenticate your games and save game progress and stats;</span></p>
<p class="p85"><span class="c0">Adhere to your preferences and to deliver dynamic content</span></p>
<p class="p86"><span class="c0">Help keep our games safe and fair and comply with the law.</span></p>
<p class="p87">&nbsp;</p>
<h2 class="p87">PARENTAL RIGHTS</h2>
<p class="p90">Parents of children under the age of 13 who are users of the Services have certain rights under COPPA, and Herotainment recognizes those rights. Parents can consent to collection and use of a child&rsquo;s personally identifiable information without consenting to the disclosure of information to third parties. Currently the only identifiable information we may collect from children is username, password, gender, birthday and parent&rsquo;s email address. If a parent instructs us, we will delete the information provided during the registration process within a reasonable time period.</p>
<p class="p92"><span class="c0">A child&rsquo;s participation or access to an activity on the Services is not conditioned on their providing more personal information than is reasonably necessary for the activity.</span></p>
<p class="p93"><span class="c0">Parents can review information their children have contributed to the Services, request that Herotainment delete that information, and refuse to allow Herotainment to collect further information from their child by contacting our customer support department by email at info@herotainment.com. Parents should include their child&rsquo;s username and the registered (parent&rsquo;s) email address in the email so we can better assist them with their inquiry or request. Herotainment may ask additional questions or take other steps to verify the identity of parents before responding to a request to review or delete their child&rsquo;s information, or a request to refuse further collection from the child.</span></p>
<h2 class="p94">LINKS TO THIRD PARTY WEB SERVICES</h2>
<p class="p96">We may provide links to third party services, including links from our Shop feature. Through that feature, we let our users know where they can purchase Herotainment merchandise. Before a user can exit our Services, we explain that the user is leaving our Services, and going to the Services of a third party. Once they leave our Services, he or she may submit information to a third party, over whom we have no authority or control, and who may have different information collection and use practices. Users and Parents should always read a company&rsquo;s Privacy Policy carefully, including those companies to whom we provide links, before submitting information to them.</p>
<p class="p98"><span class="c0">We do not store or share your financial information except as described in this Privacy Policy. However, if you bought or otherwise accessed the Services through a third-party distributor such as Apple, Google or Amazon, that company may collect and store your Financial Information. Please review any applicable Distributor&rsquo;s privacy policies to see how it handles your information.</span></p>
<h2 class="p99">INFORMATION SHARING AND DISCLOSURE</h2>
<p class="p101">Herotainment does not share, rent or trade personally identifying information about our registered users, including children under the age of 13, with non-affiliated third parties (i.e., companies who are not one of our corporate affiliates or who are not providing support to the internal operations of our company) for their promotional purposes. Herotainment makes every reasonable effort to disallow and discourage users and children from sharing personally identifying information with each other via the Services features via a filter system and moderators. The only information that can be openly shared in the Services features are screen names (and children are cautioned not to select their real names).</p>
<h2 class="p103">COMMUNITY DISCLOSURES</h2>
<p class="p105"><span class="c0">I</span>f you use a forum or blog on this Service, you should be aware that any personally identifiable information you submit there can be read, collected, or used by other users of these forums, and could be used to send you unsolicited messages. Though we pre-moderate the blog comments and the Forums are pre-moderated and post-moderated, we are not responsible for the personally identifiable information you choose to submit in these forums.</p>
<p class="p107"><span class="c0">If you no longer wish to receive our newsletter and promotional communications, you may opt-out of receiving them by following the instructions included in each newsletter or you may communicate by emailing us at info@herotainment.com &ndash; please type UNSUBSCRIBE in the subject line, or you may contact us in writing by mail to: Herotainment, LLC, 79 Madison Avenue, New York, NY 10016.</span></p>
<h2 class="p108">UPDATING PERSONALLY IDENTIFIABLE INFORMATION</h2>
<p class="p110">If your personally identifiable information changes, or if you no longer desire our service, you may correct, update, amend, delete/remove or deactivate it by emailing our customer support team at info@herotainment.com or by contacting us by mail at the contact information listed below. We will respond to your request to change the information within a reasonable amount of time.</p>
<h2 class="p112">CONFIDENTIAL AND SECURE PERSONAL INFORMATION</h2>
<p class="p114">We work hard to protect your personal information. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while we strive to protect your personal information, we cannot guarantee its absolute security. We use both technical and procedural methods to maintain the integrity and security of our databases, including giving users a unique username and password for access to the Services, SSL encryption for data transfer, firewalls, and restricted access to data.</p>
<p class="p116"><span class="c0">However, the safety and security of your information also depends on you. You should never share your password with anyone else and you should always logoff before leaving your computer or mobile device. If you believe someone has unauthorized access to your password or account, please contact us immediately.</span></p>
<p class="p117"><span class="c0">This Service may contain links to other Services operated by third parties that may be of interest to you. When you follow a link and leave this Service, you do so at your own risk because we do not control such third party Services.</span></p>
<p class="p118"><span class="c0">If you have any questions about security on the Services, you can send email us at info@herotainment.com.</span></p>
<h2 class="p119">EFFECTIVE DATE AND CHANGES</h2>
<p class="p121">This Privacy Policy is updated as of January 26, 2016 and applies to all information previously obtained by Herotainment. Herotainment reserves the right to change its Privacy Policy in its sole discretion. In such case, Herotainment will post the new Privacy Policy on the Services and the effective date of the new Privacy Policy will be clearly marked. With respect to children under the age of 13, Herotainment will not use personally identifiable information from such children in ways that are materially different from this version of the Privacy Policy unless the parents are notified of, and consent to, the new changes to the Privacy Policy.</p>
<p class="p123"><span class="c0">Your use of the Services is subject to this Privacy Policy as well as our Terms of Use. Among other things, the Terms of Use establishes disclaimers of warranties, limitations on Herotainment&rsquo;s liability, choice of law and venue, and restrictions on your use of the Services. Please review this Privacy Policy and the Terms of Use carefully, because if you do not agree with our practices, your ultimate choice is not to use this Service.</span></p>
<h2 class="p124">QUESTIONS AND SUGGESTIONS</h2>
<p class="p126">If you have questions or suggestions, please email us at info@herotainment.com or mail us at:</p>
<p class="p128"><span class="c0">attn: Customer Service</span></p>
<p class="p129"><span class="c0">Herotainment, LLC</span></p>
<p class="p130"><span class="c0">79 Madison Avenue</span></p>
<p class="p131"><span class="c0">New York, NY 10016.</span></p>
<p class="p132"><span class="c0">&nbsp;</span></p>
<p class="p133"><span class="c0">Update Date: January 26, 2017</span></p>
                  </div>

              </div>

              <div class="clearfix"></div>

          </div>

      </div>

      <?php $this->load->view('site/includes/footer-sm');?>

    </div>
