<div class="page-wrapper">

      <div class="container-fluidic container-tv-header">

          <div class="container">

              <?php $this->load->view('site/includes/menu');?>

              <div class="clearfix"></div>

              <div class="page-title">
                <h1 class="grd-txt">Terms of use</h1>
              </div>

              <div class="clearfix"></div>

              <div class="block row mt-md blog-content">

                  <div class="col-lg-12">
                    <p class="p0"><span class="c0">Welcome to Smighty Stack, a downloadable application (the &ldquo;App&rdquo;) developed by Herotainment, LLC (the &ldquo;Company,&rdquo; &ldquo;us&rdquo; or &ldquo;we&rdquo;). All users of the App or other Herotainment Services (collectively, the &ldquo;Services&rdquo;) are subject to the following terms and conditions of use (these &ldquo;Terms of Use&rdquo;).</span></p>
<p class="p1"><span class="c0">Please read these Terms of Use carefully before accessing or using any part of this Service. By accessing or using this Service, you agree that you have read, understand and agree to be bound by these Terms of Use, as amended from time to time, as well as the Company Privacy Policy, which is hereby incorporated into these Terms of Use. If you do not agree to these Terms of Use, do not access or use any part of this Service.</span></p>
<p class="p2"><span class="c0">If you are a parent or guardian, you agree to be bound by these Terms of Use by your child&rsquo;s registration with the Service, in respect of their use of the Service.</span></p>
<p class="p4"><span class="c0">You acknowledge that these Terms of Use are supported by reasonable and valuable consideration, the receipt and adequacy of which are hereby acknowledged. Without limiting the generality of the foregoing, you acknowledge that such consideration includes your use of this Service and receipt of materials, data, and information available at or through the Service, the possibility of our use or display of your submissions (as defined below) and the possibility of the publicity and promotion from our use or display of your submissions.</span></p>
<p class="p5"><span class="c0">The Company may revise and update these Terms of Use at any time without notice by posting the amended terms to this Service. Your continued use of the Service means that you accept and agree to the revised Terms of Use. If you disagree with the Terms of Use (as amended from time to time) or are dissatisfied with this Service, your sole and exclusive remedy is to discontinue using this Service. It is your responsibility to regularly check the Service to determine if there have been changes to these Terms of Use and to review such changes.</span></p>
<h2 class="p7"><span class="c0">USE OF THE SERVICE</span></h2>
<p class="p9"><span class="c0">The Service is only for your personal use and not for you to use for commercial purposes. You may not use the Service in any way that is unlawful, or harms us or any other person or entity, as determined in our sole discretion. All materials, information, functions and other content (including submissions as defined below) contained on the Service are our copyrighted property. All trademarks, service marks, trade names, and trade dress are proprietary to us. You acknowledge and agree that nothing in these Terms of Use shall have the effect of transferring the ownership of any trademarks, service marks, trade names or other proprietary rights in the Service or content or any part thereof to you or any third party. You undertake not to do any act or thing which is inconsistent with or which is likely in any way to prejudice such title. You agree to use the Service only for lawful purposes:</span></p>
<p class="p10"><span class="c0">(a) Specifically you agree not to do any of the following:</span></p>
<p class="p11"><span class="c0">(1) upload to or transmit on the Service any indecent, obscene, defamatory, harassing, violent or otherwise objectionable material, or any material that is, or may be, protected by copyright, without permission from the copyright owner;</span></p>
<p class="p12"><span class="c0">(2) upload to or transmit on the Service any solicitations or advertisements of business;</span></p>
<p class="p13"><span class="c0">(3) use the Service to violate the legal rights (including the rights of publicity and privacy) of others or to violate the laws of any jurisdiction;</span></p>
<p class="p14"><span class="c0">(4) misrepresent an affiliation with any person or organization;</span></p>
<p class="p15"><span class="c0">(5) intercept or attempt to intercept electronic mail not intended for you;</span></p>
<p class="p16"><span class="c0">(6) upload or otherwise transmit files that contain a virus or corrupted data;</span></p>
<p class="p17"><span class="c0">(7) restrict or inhibit use of the Service by others;</span></p>
<p class="p18"><span class="c0">(8) post &ldquo;spam,&rdquo; transmit chain letters or engage in other similar activities;</span></p>
<p class="p19"><span class="c0">(9) collect information about others (including e-mail addresses) without their consent;</span></p>
<p class="p20"><span class="c0">(10) solicit personal information from anyone under 18 or solicit passwords or personally identifying information for commercial or unlawful purposes;</span></p>
<p class="p21"><span class="c0">(11) download a file or software or include in a message any software, files or links that you know, or have reason to believe, cannot be distributed legally over the Service or that you have a contractual obligation to keep confidential (notwithstanding its availability on the Service);</span></p>
<p class="p22"><span class="c0">(12) harass, abuse or &ldquo;stalk,&rdquo; another user, or attempt to do any of the foregoing; or</span></p>
<p class="p23"><span class="c0">(13) engage in any other conduct that restricts or inhibits anyone&rsquo;s use or enjoyment of the Service, or which, as determined by the Company, may harm the Company or users of the Service or expose them to liability. Without limiting any of the foregoing, you also agree to abide by any code of conduct applicable to the Service or any service available on the Service.</span></p>
<p class="p24"><span class="c0">(b) Any content and/or opinions uploaded, expressed or submitted to a message board, blog, chatroom or any other publicly available section of the Service (including password-protected areas), and all articles and responses to questions, other than the content provided by the Company, are solely the opinions and responsibility of the person or entity submitting them and do not necessarily reflect the opinions of the Company. You understand and acknowledge that you are responsible for whatever content you submit, and you, not the Company, have full responsibility for such content, including its legality, reliability and appropriateness. By uploading or otherwise transmitting material to any area of the Service, you warrant that the material is your own or is in the public domain or otherwise free of proprietary or other restrictions and that you have the right to post it to the Service. You grant to the Company the right to use all content you upload or otherwise transmit to the Service in any manner the Company chooses, including, but not limited, to copying, displaying, performing or publishing it in any format whatsoever, modifying it, incorporating it into other material or making a derivative work based on it.</span></p>
<p class="p25"><span class="c0">(c) The Company reserves the right, but does not assume any responsibility, to (1) remove any material posted on the Service which the Company, in its sole discretion, deems inconsistent with the foregoing commitments (including any material that the Company has reason to believe constitutes, or for which the Company has received notice of its constituting, a copyright infringement); and (2) terminate any user&rsquo;s access to all or part of the Service. However, the Company can neither review all material before it is posted on the Service nor ensure prompt removal of objectionable material after it has been posted. Accordingly, the Company assumes no liability for any action or inaction regarding transmissions, communications or content provided by third parties. The Company reserves the right to take any action it deems necessary to protect the personal safety of users of this Service and the public; however, the Company has no liability or responsibility to anyone for performance or nonperformance of the activities described in this paragraph.</span></p>
<p class="p26"><span class="c0">(d) Your failure to comply with the provisions of (a) or (b) above may result in the termination of your access to the Service and may expose you to civil and/or criminal liability.</span></p>
<h2 class="p28"><span class="c0">SUBMISSIONS</span></h2>
<p class="p30"><span class="c0">In these Terms of Use, &ldquo;Submissions&rdquo; mean messages, text, concepts, ideas, comments, pitches, suggestions, screenplays, stories, treatments, formats, artwork, drawings, photographs, videos, audiovisual works, musical compositions (including lyrics), sound recordings, characterizations, your and/or other persons&rsquo; names, likenesses, voices, profiles, usernames, actions, appearances, performances and/or other biographical information or material, and/or other similar materials that you submit, post, upload, embed, display, communicate or otherwise distribute (collectively, &ldquo;Distribute&rdquo;) on or through this Service.</span></p>
<p class="p31"><span class="c0">All Submissions or other information sent by you to the Company or business partners in response to solicitations on this Service will become the Company&rsquo;s property and you agree that all intellectual property rights therein are transferred to the Company. If we solicit Submissions through features or activities on or through the Service that require use of our copyrighted works, we grant to you a non-exclusive license to create a derivative work of such works to the extent required to make your Submission and only for the purpose of making your Submission. For avoidance of doubt, the Company shall own any developments by the Company or on its behalf arising out of your Submissions. To the extent the Company does not own such materials, you grant and agree to grant the Company a non-exclusive, royalty-free license to utilize, create derivative works of, distribute and sublicense such materials for any purpose in connection with the Company&rsquo;s web Services, products and services. You have no expectation of any review, compensation or consideration of any type for all Submissions hereunder.</span></p>
<p class="p32"><span class="c0">You understand that any postings, or content submitted for posting, to publicly available portions of the Service, including chat areas, message boards and the like (&ldquo;Public Areas&rdquo;) are non confidential for all purposes. You have no expectation of privacy related to Public Areas.</span></p>
<h2 class="p34"><span class="c0">ACCOUNTS</span></h2>
<p class="p36"><span class="c0">In order to use the Service, you might be required to create an account. You agree to provide true, accurate, current and complete information during the registration process for any account, and to keep the information current through updates. You may not impersonate any person or entity or misrepresent your identity, including by using another person&rsquo;s account information. You are fully responsible for all activities conducted through your account. You are responsible for maintaining the confidentiality of your password and for any use of your password to gain access to your account and your account information. If you disclose your password to any other person, it is at your own risk. You do not own the account you use to access the Service, and you do not own any data the Company stores on its servers. You also agree to promptly notify the Company at smightystack@herotainment.com of any unauthorized use of your username, password other account information, or any other breach of security that you become aware of involving or relating to the Service. We may suspend or terminate your account for any failure to comply with these Terms of Use, any terms related to any service offered through the Service or for any reason whatsoever, or for no reason. Notwithstanding the foregoing, you acknowledge that the Company does not guarantee the accuracy of any information submitted by any user, including account information about the user. In addition, you agree to exit from your account at the end of each session.</span></p>
<h2 class="p38"><span class="c0">PAID FEATURES AND REFUND POLICY</span></h2>
<p class="p40"><span class="c0">Some areas or features of the Service are only available to paying users. To become a paying user, you must agree to be bound by these Terms of Use and the Privacy Policy and pay the amount stated, plus any applicable fees and taxes.</span></p>
<p class="p41"><span class="c0">You authorize us or our payment vendor to automatically charge your credit card, debit card or alternative payment method for the amount of the fees for the feature you select, plus any applicable fees and taxes.</span></p>
<p class="p42"><span class="c0">Payments are non-cancelable and non-refundable, even if you close your account or delete your account.</span></p>
<p class="p43"><span class="c0">All fees are subject to change at the discretion of the Company. Your fees will not change in the middle of any payment term, and any changes will be effective upon the next payment made. A number of our Services may allow you to purchase virtual currencies and virtual items for use in our Services. You are also able to purchase Service merchandise through our website. You acknowledge and agree that all purchases made by you through the Services are non-refundable. Also, if you are under the age of 13, you will need your parent to make any purchase in our Services. You acknowledge and agree that we are not required to refund your money or compensate you for any unused virtual goods if your access to the services is terminated or the Services are no longer available.</span></p>
<p class="p44"><span class="c0">Refunds will not be given to players who have been banned from the game for any reason, including violating the terms and conditions of use.</span></p>
<h2 class="p46"><span class="c0">TERMINATION OF ACCESS</span></h2>
<p class="p48"><span class="c0">We have the right, in our absolute discretion, to terminate your access to the Services at any time without prior notice to you where we believe that you have not complied with any of these Terms of Service or any or our rules of use, codes of conduct or any or our instructions for our Services.</span></p>
<h2 class="p50"><span class="c0">PUBLIC FORUMS AND COMMUNICATION</span></h2>
<p class="p52"><span class="c0">&ldquo;Public Forum&rdquo; means an area, Service or feature offered as part of the Service that offers the opportunity for users to distribute Submissions for viewing by one or more Service users, including a chat area, message board or social community environment.</span></p>
<p class="p53"><span class="c0">You acknowledge that Public Forums and features offered therein are for public and not private communications, and you have no expectation of privacy with regard to any Submission to a Public Forum. We cannot guarantee the security of any information you disclose through any of these media; you make such disclosures at your own risk.</span></p>
<p class="p54"><span class="c0">You are and shall remain solely responsible for the Submissions you distribute on or through the Service under your username or otherwise by you in any Public Forum and for the consequences of submitting and posting same. We have no duty to monitor any Public Forum.</span></p>
<p class="p55"><span class="c0">Also, you should be skeptical about information provided by others, and you acknowledge that the use of any Submission posted in any Public Forum is at your own risk. For example, we are not responsible for, and we do not endorse, the opinions, advice or recommendations posted or sent by users in any Public Forum and we specifically disclaim any and all liability in connection therewith.</span></p>
<p class="p56"><span class="c0">We owe you no obligation, and therefore may refuse to post, deliver, remove, modify or otherwise use or take any action with respect to Submissions you distribute.</span></p>
<p class="p57"><span class="c0">We reserve the right to screen, refuse to post, remove or edit Submissions at any time and for any or no reason including, without limitation, if your Submission fails to conform to our rules of conduct discussed in the Use of the Service section above, in our absolute and sole discretion without prior notice, although we have no duty to do so or to monitor any Public Forum. If we elect to screen Submissions, there may be a delay in the posting of such content in a Public Forum to allow for a review process. If we have questions about your Submissions including, without limitation, the copyright, we may contact you for further information including, for example, to verify that you own the copyright or otherwise obtained permission to post the material.</span></p>
<h2 class="p59"><span class="c0">PRIVACY</span></h2>
<p class="p61"><span class="c0">The Company&rsquo;s use of your personal information and your responsibilities in connection with protecting your privacy are described in the Company Privacy Policy, which is incorporated by reference into these Terms of Use.</span></p>
<h2 class="p63"><span class="c0">COPYRIGHT RESTRICTIONS/USE OF CONTENT</span></h2>
<p class="p65"><span class="c0">The entire contents of this Service (including all information, text, displays, images and audio and any software made available through or in connection with the Service) and the design, selection and arrangement thereof, are proprietary to the Company or its affiliates or licensors and are protected by United States and international laws regarding copyrights, trademarks, trade secrets and other proprietary rights. You are authorized only to use the content on the Service for personal use or legitimate business purposes related to your role as a current or prospective user of the Service. You may not copy, modify, create derivative works of, publicly display or perform, republish, store, transmit or distribute any of the material on this Service without the prior written consent of the Company, except to: (a) store copies of such materials temporarily in RAM, (b) store files that are automatically cached by your web browser for display enhancement purposes, and (c) print a reasonable number of pages of the Service; provided in each case that you do not alter or remove any copyright or other proprietary notices included in such materials. Neither the title nor any intellectual property rights to any information or material in this Service are transferred to you, but remain with the Company or the applicable owner of such content. Except as expressly authorized by the Company in writing, you may not reproduce, sublicense, distribute, sell or exploit for any commercial purposes (a) any part of this Service, (b) access to this Service or (c) use of this Service or of any services or materials available through this Service.</span></p>
<h2 class="p67"><span class="c0">TRADEMARKS</span></h2>
<p class="p69"><span class="c0">The Company name and logos, and all related names, logos, product and service names, designs and slogans contained in the Service or any software provided or accessed in connection therewith are trademarks of the Company, its affiliates, licensors and/or contractors unless otherwise clearly specified in writing. You may not use such marks without the prior written permission of the Company. All other names, brands and marks are used for identification purposes only and may be the trademarks of their respective owners.</span></p>
<h2 class="p71"><span class="c0">SOFTWARE AND DOWNLOADS</span></h2>
<p class="p73"><span class="c0">In the event the Company offers downloads of, or access to, software on this Service and you download or otherwise access such software, the software (including any data or images incorporated in or generated by the software) is licensed to you. You do not receive title to this software and you may not distribute or use the software other than for the purpose of using the applicable feature or service of the Service as offered by the Company. You may not modify, adapt, reverse engineer, decompile, disassemble or otherwise attempt to discover the source code of such software. Except as expressly provided, you may not create any derivative works of the software or any services available on the Service. This license is revocable at any time without notice and with or without cause. You agree to destroy or return to the Company all copies of the software upon revocation of your license to the software and/or termination of your account. The software is subject to all restrictions on use, disclaimers of warranties and other provisions in these Terms of Use. In the event that the software is also subject to a separate end user license agreement, the terms of such end user license agreement shall control any conflict between those terms and these Terms of Use.</span></p>
<h2 class="p75"><span class="c0">ACCESS AND INTERFERENCE</span></h2>
<p class="p77"><span class="c0">You agree that you will not (b) use any manual process to monitor or copy any of the material on this Service or for any other unauthorized purpose without the prior written consent of the Company, (a) use any robot, spider or other automatic device, process or means to access the Service, (c) use any device, software or routine that interferes with the proper working of the Service, (e) take any action that imposes an unreasonable or disproportionately large load on the Company&rsquo;s infrastructure, (d) attempt to interfere with the proper working of the Service or (f) access, reload or &ldquo;refresh&rdquo; transactional pages, or make any other request to transactional servers, more than once during any three (3) second interval.</span></p>
<h2 class="p79"><span class="c0">LIMITATION OF LIABILITY</span></h2>
<p class="p81"><span class="c0">The Company does not assume any liability for the materials, information and opinions provided on, or available through, the Service (the &ldquo;Service Content&rdquo;). Reliance on the Service Content is solely at your own risk. The Company disclaims any liability for injury or damages resulting from the use of any Service Content.</span></p>
<p class="p82"><span class="c0">THE SERVICE, THE SERVICE CONTENT AND THE PRODUCTS AND SERVICES PROVIDED ON OR AVAILABLE THROUGH THIS SERVICE ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS, WITH ALL FAULTS. NEITHER THE COMPANY, ITS LICENSORS OR CONTRACTORS, NOR ANY PERSON ASSOCIATED WITH THE COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICE, THE CONTENT, PRODUCTS OR SERVICES. SPECIFICALLY, BUT WITHOUT LIMITING THE FOREGOING, NEITHER THE COMPANY, ITS LICENSORS, ITS CONTRACTORS NOR ANYONE ASSOCIATED WITH THE COMPANY WARRANTS OR REPRESENTS THAT THE SERVICE, THE SERVICE CONTENT OR THE PRODUCTS AND SERVICES PROVIDED ON OR THROUGH THIS SERVICE WILL BE ACCURATE, RELIABLE, ERROR-FREE OR UNINTERRUPTED; THAT DEFECTS WILL BE CORRECTED; THAT THE SERVICE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR THAT THE SERVICE WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS. THE COMPANY AND ITS LICENSORS AND CONTRACTORS DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.</span></p>
<p class="p83"><span class="c0">IN NO EVENT WILL THE COMPANY OR ITS LICENSORS OR CONTRACTORS BE LIABLE FOR ANY DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF, OR INABILITY TO USE, THE SERVICE, THE SERVICE CONTENT, ANY SERVICES PROVIDED ON OR THROUGH THIS SERVICE OR ANY LINKED SERVICE, INCLUDING ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING, BUT NOT LIMITED TO, PERSONAL INJURY, LOST PROFITS OR DAMAGES RESULTING FROM DELAY, INTERRUPTION IN SERVICE, VIRUSES, DELETION OF FILES OR ELECTRONIC COMMUNICATIONS, OR ERRORS, OMISSIONS OR OTHER INACCURACIES IN THE SERVICE OR THE SERVICE CONTENT OR SERVICES, WHETHER OR NOT THERE IS NEGLIGENCE BY THE COMPANY AND WHETHER OR NOT THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF ANY SUCH DAMAGES.</span></p>
<p class="p84"><span class="c0">You acknowledge and agree that neither the Company nor its licensors or contractors operate or control the Internet and that: (i) viruses, worms, trojan horses or other undesirable data or software; or (ii) unauthorized users (e.g., hackers) may attempt to obtain access to your data, web Service, computer or network. The Company uses what it believes to be reasonable efforts to protect itself and its Service users from such unauthorized use, but the Company and its licensors and contractors are not responsible for failures resulting from the acts or omissions of third parties not controlled by or under contract with the Company.</span></p>
<h2 class="p86"><span class="c0">INTERACTION WITH OTHER USERS</span></h2>
<p class="p88"><span class="c0">As a condition of access to the Service, you release the Company (and its shareholders, partners, affiliates, directors, officers, subsidiaries, employees, agents, suppliers, third party information providers, licensors, licensees, distributors and contractors) from claims, demand and damages (actual and consequential) of every kind and nature arising out of or in any way connected with any dispute you may have with any other user of the Service. The Company will have the right but not the obligation to resolve disputes between users relating to use of the Service, and to the extent that it elects to resolve such disputes, the Company will do so in good faith based on the general rules and standards of the Company and the Service. You release the Company (and its shareholders, partners, affiliates, directors, officers, subsidiaries, employees, agents, suppliers, third party information providers, licensors, licensees, distributors and contractors) from claims, demand and damages (actual and consequential) of every kind and nature arising out of or in any way connected with the Company&rsquo;s resolution of such disputes.</span></p>
<h2 class="p90"><span class="c0">INDEMNIFICATION</span></h2>
<p class="p92"><span class="c0">You agree to indemnify and hold harmless the Company and its shareholders, partners, affiliates, directors, officers, subsidiaries, employees, agents, suppliers, third party information providers, licensors, licensees, distributors, contractors and others involved in the Service or the delivery of products, services or information over the Service, from and against any and all liabilities, expenses, damages and costs, including reasonable attorney&rsquo;s fees, arising from any violation by you of these Terms of Use or your use of the Service or any products, services or information obtained from the Service.</span></p>
<h2 class="p94"><span class="c0">LINKS TO OTHER SERVICES</span></h2>
<p class="p96"><span class="c0">The Service may contain links to other web Services on the Internet. The Company is not responsible for and does not endorse the content, products, services or practices of any third party web Services, including, without limitation, Services framed within the Service and does not make any representations regarding their quality, content or accuracy. Your use of third party web Services is at your own risk and subject to the terms and conditions of use for such web Services.</span></p>
<p class="p97"><span class="c0">The Company is not responsible for any products or services you may elect to purchase, download or use from any third party distributor, merchant or other information or service provider (&ldquo;Merchant&rdquo;). All transactions regarding goods or services offered by Merchants, including, but not limited to, the purchase and payment terms for such goods or services, warranties, guarantees, maintenance and delivery, are solely between you and the Merchant and are governed by the terms of the agreement between you and the Merchant. The Company is not a party to any transactions between you and a Merchant, and is not liable for any direct or indirect costs or damages arising out of any dispute between you and a Merchant. NEITHER THE COMPANY, ITS LICENSORS OR CONTRACTORS, NOR ANY THIRD PARTY PROVIDER, OTHER THAN THE MERCHANT OFFERING SUCH GOODS OR SERVICES, MAKES ANY EXPRESS OR IMPLIED REPRESENTATIONS OR WARRANTIES REGARDING THE GOODS OR SERVICES OFFERED BY SUCH MERCHANT, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT OR COMPATIBILITY.</span></p>
<h2 class="p99"><span class="c0">SUSPECTED COPYRIGHT INFRINGEMENT</span></h2>
<p class="p101"><span class="c0">In accordance with the Digital Millennium Copyright Act (&ldquo;DMCA&rdquo;) and other applicable law, the Company may, in appropriate circumstances and in the Company&rsquo;s sole discretion, terminate your access to this Service if it deems you to be a repeat infringer. The Company may also, in its sole discretion, limit your access to the Service and/or terminate your membership if you infringe any intellectual property rights of others, whether or not there is any repeat infringement.</span></p>
<p class="p102"><span class="c0">If you are a copyright owner or an agent thereof and believe that any user Submission or other content infringes upon your copyrights, you may submit a notification pursuant to the DMCA by providing our Copyright Agent with the following information in writing (see 17 U.S.C. 512(c)(3) for further detail):</span></p>
<p class="p103"><span class="c0">A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</span></p>
<p class="p104"><span class="c0">Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online Service are covered by a single notification, a representative list of such works;</span></p>
<p class="p105"><span class="c0">Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit us to locate the material;</span></p>
<p class="p106"><span class="c0">Information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an electronic mail address;</span></p>
<p class="p107"><span class="c0">A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</span></p>
<p class="p108"><span class="c0">A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</span></p>
<p class="p109"><span class="c0">Herotainment&rsquo;s Copyright Agent for notice of claims of copyright infringement on the Service can be reached as follows:</span></p>
<p class="p110"><span class="c0">Herotainment, LLC</span></p>
<p class="p111"><span class="c0">Attention: 79 Madison Avenue, New York, NY 10016 or at</span></p>
<p class="p112"><span class="c0">smightystack@herotainment.com</span></p>
<p class="p113"><span class="c0">You acknowledge that if you fail to comply with all of the requirements of this Section, your DMCA notice may not be valid.</span></p>
<h2 class="p115"><span class="c0">MISCELLANEOUS</span></h2>
<p class="p117"><span class="c0">The owner of this Service is based in the State of New York, USA. The Company makes no representation that materials in this Service are appropriate or available for use in other locations. If you access this Service from other locations, you are responsible for complying with local laws. These Terms of Use shall be governed in all respects by and construed in accordance with the laws of the State of New York, USA, without regard to its conflicts of law principles, and exclusive jurisdiction over any cause of action arising out of these Terms of Use or your use of the Company Web Service shall be in the state or federal courts located in New York. You agree to submit to the jurisdiction of such courts, and you hereby waive all defenses of lack of personal jurisdiction and forum non-conveniens with respect to venue and jurisdiction in the state and federal courts located in New York.</span></p>
<p class="p118"><span class="c0">You agree to abide by U.S. and other applicable laws, including export control laws, and not to transfer, by electronic transmission or otherwise, any software or other content downloaded from the Service to a destination prohibited by such laws, without first obtaining, and then complying with, any requiService government authorization. By downloading any software from the Service, you warrant that you are not located in any country, or exporting such software to any person or place, to which the United States has embargoed goods. You further agree not to upload to the Service any data or software that cannot be exported without prior written government authorization, including, but not limited to, certain types of encryption software.</span></p>
<p class="p119"><span class="c0">These Terms of Use, as they may be amended from time to time, completely and exclusively state the agreement between you and the Company with respect to the Service, and no other terms that may have been communicated to you orally or in any other manner shall have any force or effect. Any cause of action you may have with respect to the Service must be commenced within one (1) year after the claim or cause of action arises or such claim or cause of action is barred.</span></p>
<p class="p120"><span class="c0">You agree and acknowledge that your violation of any restrictions in these Terms of Use on the use of the Service, Service Content, or software or services available on or through the Service, or your use or disclosure of Confidential Information in a manner inconsistent with the provisions of these Terms of Use, may cause the Company irreparable damage for which remedies at law may be inadequate. You agree that, in the event of your unauthorized use of the Service, Service Content, software and services, or your unauthorized disclosure of Confidential Information, the Company will be entitled to injunctive relief, in addition to such other legal and equitable remedies that may be available. The Company&rsquo;s licensors and contractors are express third party beneficiaries of any terms in these Terms of Use that are applicable to their products or services, including disclaimers of warranty and limitations of liability, and shall have the right to enforce directly against you all of your applicable representations, warranties, covenants, indemnifications and obligations under these Terms of Use.</span></p>
<p class="p121"><span class="c0">If any part of these Terms of Use is unenforceable, the unenforceable part shall be construed to reflect, as nearly as possible, the original intentions of the parties. The other provisions of these Terms of Use shall remain in full force and effect.</span></p>
<p class="p122"><span class="c0">The Company&rsquo;s failure to insist upon or enforce strict performance of any provision of these Terms of Use shall not constitute a waiver of the provision. Neither a course of dealing or conduct between you and the Company nor any trade practices shall be deemed to modify these Terms of Use.</span></p>
<p class="p122">&nbsp;</p>
<h2 class="p124"><span class="c0">CONTACTING HEROTAINMENT</span></h2>
<p class="p125"><span class="c0">Herotainment, LLC</span></p>
<p class="p126"><span class="c0">79 Madison Avenue</span></p>
<p class="p127"><span class="c0">New York, NY 10016</span></p>
<p class="p128"><span class="c0">smightystack@herotainment.com</span></p>
<p class="p129"><span class="c0">December 17, 2016</span></p>
                  </div>

              </div>

              <div class="clearfix"></div>

          </div>

      </div>

      <?php $this->load->view('site/includes/footer-sm');?>

    </div>
